title = 'emptiness-of-space'
theme = 'blue'

favicon = "style/favicon.ico"
languageCode = 'en-us'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    noHl = false
    style = 'api'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
